Neos:
  NeosIo:
    fundingApi:
      username: ''
      password: ''
      apiUrl: 'https://neosfunding.sandstorm.de/funding-api-sold-badges'
      timeout: 30
      actions:
        getBadges: '/funding-api-sold-badges'
      parameters: []
