Neos:
  NeosIo:
    fundingApi:
      username: ''
      password: ''
      apiUrl: 'https://neosfunding.sandstorm.de'
      timeout: 30
      actions:
        getBadges: '/funding-api-sold-badges'
      parameters: []

    crowdApi:
      username: ''
      password: ''
      apiUrl: 'https://crowd.neos.io/rest/usermanagement/1'
      timeout: 30
      actions:
        search: '/search.json'
        getGroup: '/group.json'
        getGroupMembers: '/group/user/direct.json'
        getUser: '/user.json'
        setGroupAttributes: '/group/attribute.json'
      parameters:
        active: true # Always search for active records
      additionalAttributes:
        group:
          - neos_group_type # Something like 'team' or 'guild'
          - neos_title # A human readable name for the group
          - neos_summary # A short summary describing the group
        user: []
